- name: 単一データベースの設定
  hosts: dbserver
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: 必要なパッケージをインストール
      dnf:
        name:
          - python3-PyMySQL
          - mariadb-server
        state: present

    - name: MariaDBサービスの起動
      service:
        name: mariadb
        state: started
        enabled: yes

    - name: MariaDBのrootパスワードを設定
      mysql_user:
        name: root
        host: localhost
        password: "{{ lookup('awx', 'mariadb_root_password') }}"
        login_unix_socket: /var/lib/mysql/mysql.sock
        state: present

    - name: データベースを作成
      mysql_db:
        name: reservation_system
        state: present
        login_user: root
        login_password: "{{ lookup('awx', 'mariadb_root_password') }}"

    - name: データベースユーザー作成
      mysql_user:
        name: okamotodaichi
        host: "192.168.64.6"
        password: "{{ lookup('awx', 'db_user_password') }}"
        priv: "reservation_system.*:ALL"
        state: present
        login_user: root
        login_password: "{{ lookup('awx', 'mariadb_root_password') }}"

    - name: MariaDB設定ファイルの変更
      lineinfile:
        path: /etc/my.cnf.d/mariadb-server.cnf
        regexp: '^bind-address'
        line: 'bind-address = 0.0.0.0'
        backup: yes

    - name: MariaDBを再起動する
      service:
        name: mariadb
        state: restarted
