- name: 単一データベースの設定
  hosts: dbserver
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
    mariadb_root_pass: "{{ mariadb_root_password }}"
    db_user_pass: "{{ db_user_password }}"
  tasks:
    - name: 必要なパッケージをインストール
      dnf:
        name:
          - python3-PyMySQL
          - mariadb-server
        state: present

    - name: MariaDBサービスの起動
      service:
        name: mariadb
        state: started
        enabled: yes

    - name: rootパスワードが設定済みか確認
      command: mysql -u root -p{{ mariadb_root_pass }} -e "SELECT 1"
      register: root_login_check
      ignore_errors: yes
      no_log: yes  # パスワードをログに表示しない

    - name: MariaDBのrootパスワードを設定
      mysql_user:
        name: root
        host: localhost
        password: "{{ mariadb_root_pass }}"
        login_unix_socket: /var/lib/mysql/mysql.sock
        state: present
      when: root_login_check.rc != 0  # ログイン失敗時のみ実行

    - name: データベースを作成
      mysql_db:
        name: reservation_system
        state: present
        login_user: root
        login_password: "{{ mariadb_root_pass }}"

    - name: データベースユーザー作成
      mysql_user:
        name: okamotodaichi
        host: "192.168.64.5"  # WebサーバーのIPに修正
        password: "{{ db_user_pass }}"
        priv: "reservation_system.*:ALL"
        state: present
        login_user: root
        login_password: "{{ mariadb_root_pass }}"

    - name: MariaDB設定ファイルの変更
      lineinfile:
        path: /etc/my.cnf.d/mariadb-server.cnf
        regexp: '^bind-address'
        line: 'bind-address = 0.0.0.0'
        backup: yes

    - name: ファイアウォールでMariaDBポートを許可
      firewalld:
        port: 3306/tcp
        permanent: yes
        state: enabled
        immediate: yes

    - name: MariaDBを再起動する
      service:
        name: mariadb
        state: restarted
