- name: 単一データベースの設定
  hosts: dbserver
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: 必要なパッケージをインストール
      dnf:
        name:
          - python3-PyMySQL
          - mariadb-server    # CentOSではMySQLの代わりにMariaDBを使用
        state: present

    - name: MariaDBサービスの起動
      service:
        name: mariadb        # サービス名もmariadbに変更
        state: started
        enabled: yes         # システム起動時に自動起動

    - name: 予約管理システム用データベースを作成
      mysql_db:
        name: reservation_system
        state: present

    - name: MySQLユーザー作成
      mysql_user:
        name: okamotodaichi
        host: 192.168.64.6
        password: "{{ lookup('awx', 'password') }}"
        priv: "reservation_system.*:ALL"
        state: present

    - name: MariaDB設定ファイルの変更
      lineinfile:
        path: /etc/my.cnf.d/mariadb-server.cnf   # CentOSでの設定ファイルパス
        regexp: '^bind-address'
        line: 'bind-address = 0.0.0.0'
        backup: yes

    - name: MariaDBを再起動する
      service:
        name: mariadb        # サービス名をmariadbに変更
        state: restarted
