- name: 単一データベースの設定
  hosts: dbserver
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: 必要なパッケージをインストール
      apt:
        name:
          - python3-pymysql
          - mysql-server
        state: present
        update_cache: yes

    - name: 予約管理システム用データベースを作成
      mysql_db:
        name: reservation_system
        state: present

    - name: MySQLユーザー作成
      mysql_user:
        name: okamotodaichi
        host: 192.168.64.6
        password: "{{ lookup('awx', 'password') }}"
        priv: "reservation_system.*:ALL"
        state: present

    - name: MySQL設定ファイルの変更
      lineinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: '^bind-address'
        line: 'bind-address = 0.0.0.0'
        backup: yes

    - name: MySQLを再起動する
      service:
        name: mysql
        state: restarted
