- name: WebサーバーのLAMP環境セットアップ
  hosts: webserver
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
    db_host: "192.168.64.6"
    db_name: "reservation_system"
    db_user: "okamotodaichi"
  tasks:
    - name: 必要なパッケージをインストール
      dnf:
        name:
          - httpd
          - policycoreutils-python-utils  # SELinux管理用パッケージを追加
        state: present

    - name: Apacheサービスの起動と自動起動設定
      service:
        name: httpd
        state: started
        enabled: yes

    - name: PHPと必要なモジュールのインストール
      dnf:
        name:
          - php
          - php-mysqlnd
          - php-xml
          - php-mbstring
        state: present

    - name: SELinuxの設定変更（Apache用）
      shell: setsebool -P httpd_can_network_connect on
      changed_when: false  # 状態変更の判定をスキップ

    - name: ファイアウォールでHTTPを許可
      firewalld:
        service: http
        permanent: yes
        state: enabled
        immediate: yes

    - name: Apache(httpd)の再起動
      service:
        name: httpd
        state: restarted

    - name: DB接続テスト用PHPファイルの作成
      copy:
        content: |
          <?php
          $host = '{{ db_host }}';
          $dbname = '{{ db_name }}';
          $username = '{{ db_user }}';
          $password = '{{ db_user_password }}';

          try {
              $pdo = new PDO(
                  "mysql:host=$host;dbname=$dbname",
                  $username,
                  $password,
                  array(PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION)
              );
              echo "データベース接続成功！\n";
              echo "MariaDBバージョン: " . $pdo->getAttribute(PDO::ATTR_SERVER_VERSION);
          } catch(PDOException $e) {
              echo "接続失敗: " . $e->getMessage();
          }
          ?>
        dest: /var/www/html/db-test.php
        mode: '0644'
