- name: WebサーバーのLAMP環境セットアップ
  hosts: webserver
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3  # この行を追加
  tasks:
    - name: Apacheのインストール
      apt:
        name: apache2
        state: present

    - name: PHPのインストール
      apt:
        name: php
        state: present

    - name: PHP MySQLモジュールのインストール
      apt:
        name:
          - php
          - php-mysqli 
          - php-xml
          - php-mbstring
        state: present

    - name: Apacheの再起動
      service:
        name: apache2
        state: restarted
