- name: WebサーバーのLAMP環境セットアップ
  hosts: UTM-server
  become: true
  tasks:
    - name: Apacheのインストール
      apt:
        name: apache2
        state: present

    - name: PHPのインストール
      apt:
        name: php
        state: present

    - name: PHP MySQLモジュールのインストール
      apt:
        name:
          - php
          - php-mysqli 
          - php-xml
          - php-mbstring
        state: present

    - name: Apacheの再起動
      service:
        name: apache2
        state: restarted
